### ISSUE TITLE
panic when downsizing node pool

### ISSUE THREAD

**Issue by nicolasochem** [pulumi/pulumi-civo#168]
### What happened?

Civo provider crashes as follows

```
    panic: interface conversion: interface {} is nil, not string                                                                                                                     
    goroutine 16 [running]:                                                                                                                                                          
    github.com/civo/terraform-provider-civo/civo.waitForKubernetesNodePoolCreate(0xc000315cc0?, 0xc0006ac080)                                                                        
        /home/runner/go/pkg/mod/github.com/civo/terraform-provider-civo@v1.0.24/civo/resource_kubernetes_cluster_nodepool.go:367 +0x79f                                              
    github.com/civo/terraform-provider-civo/civo.resourceKubernetesClusterUpdate({0x143c810, 0xc0009861e0}, 0xc0006ac080, {0x12103e0?, 0xc000315cc0})                                
        /home/runner/go/pkg/mod/github.com/civo/terraform-provider-civo@v1.0.24/civo/resource_kubernetes_cluster.go:449 +0xe45                                                       
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc0001cd340, {0x143c7d8, 0xc000044120}, 0xd?, {0x12103e0, 0xc000315cc0})                          
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:746 +0x12e                                    
    github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc0001cd340, {0x143c7d8, 0xc000044120}, 0xc0008d1a00, 0xc000831d00, {0x12103e0, 0xc000315cc0})     
        /home/runner/go/pkg/mod/github.com/pulumi/terraform-plugin-sdk/v2@v2.0.0-20220725190814-23001ad6ec03/helper/schema/resource.go:852 +0x83a                                    
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfshim/sdk-v2.v2Provider.Apply({0xc0003bfb00?}, {0x122b1c0, 0x17}, {0x143d3a8?, 0xc0008c3600}, {0x14428a8?, 0xc000831d00})      
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.31.0/pkg/tfshim/sdk-v2/provider.go:122 +0x19b                                                        
    github.com/pulumi/pulumi-terraform-bridge/v3/pkg/tfbridge.(*Provider).Update(0xc00084c000, {0x143c848?, 0xc0008c4ba0?}, 0xc000830e80)                                            
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi-terraform-bridge/v3@v3.31.0/pkg/tfbridge/provider.go:1059 +0x86f                                                            
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler.func1({0x143c848, 0xc0008c4ba0}, {0x119fc80?, 0xc000830e80})                                           
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.40.2/proto/go/provider.pb.go:3782 +0x7b                                                                           
    github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x143c848, 0xc0008c4720}, {0x119fc80, 0xc000830e80}, 0xc00020e800, 0xc0008ba2a0)        
        /home/runner/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3f9                                          
    github.com/pulumi/pulumi/sdk/v3/proto/go._ResourceProvider_Update_Handler({0x11e58c0?, 0xc00084c000}, {0x143c848, 0xc0008c4720}, 0xc000145960, 0xc00069e1a0)                     
        /home/runner/go/pkg/mod/github.com/pulumi/pulumi/sdk/v3@v3.40.2/proto/go/provider.pb.go:3784 +0x138                                                                          
    google.golang.org/grpc.(*Server).processUnaryRPC(0xc00084a000, {0x1442c60, 0xc000602340}, 0xc0007d99e0, 0xc0004be510, 0x1c1e5d0, 0x0)                                            
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1301 +0xb2b                                                                                                 
    google.golang.org/grpc.(*Server).handleStream(0xc00084a000, {0x1442c60, 0xc000602340}, 0xc0007d99e0, 0x0)
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:1642 +0xa2f
    google.golang.org/grpc.(*Server).serveStreams.func1.2()
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:938 +0x98
    created by google.golang.org/grpc.(*Server).serveStreams.func1
        /home/runner/go/pkg/mod/google.golang.org/grpc@v1.49.0/server.go:936 +0x28a

    error: update failed
```

### Steps to reproduce

Downsize the number of nodes of the detault nodepool of your cluster as follows:

```
    const civoK8s = new civo.KubernetesCluster(
       name,
       {
         pools:
         {
-          nodeCount: 3,
+          nodeCount: 2,
           size: "g4s.kube.medium",
```

### Expected Behavior

Downsize

### Actual Behavior

Panic

### Output of `pulumi about`

```
CLI          
Version      3.48.0
Go Version   go1.19.2
Go Compiler  gc

Plugins
NAME          VERSION
civo          2.3.0
cloudflare    4.12.1
digitalocean  4.16.0
docker        3.6.1
gcp           6.43.0
kubernetes    3.22.1
kubernetes    3.21.4
nodejs        unknown

Host     
OS       fedora
Version  35
Arch     x86_64

This project is written in nodejs: executable='/home/nochem/.nvm/versions/node/v18.10.0/bin/node' version='v18.10.0'



Dependencies:
NAME                              VERSION
eslint                            8.28.0
yaml                              2.1.3
@pulumi/digitalocean              4.16.0
@pulumi/gcp                       6.43.0
@typescript-eslint/parser         5.44.0
eslint-config-prettier            8.5.0
@typescript-eslint/eslint-plugin  5.44.0
eslint-plugin-prettier            4.2.1
prettier                          2.8.0
@pulumi/docker                    3.6.1
@pulumi/pulumi                    3.48.0
eslint-config-airbnb-base         15.0.0
eslint-plugin-import              2.26.0
rand-seed                         1.0.2
@pulumi/civo                      2.3.0
@pulumi/cloudflare                4.12.1
@pulumi/kubernetes                3.22.1
@types/node                       16.11.17

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
I'm guessing that this is the same issue as https://github.com/civo/terraform-provider-civo/issues/137

**Comment by AaronFriel** [comment]
@nicolasochem, it looks like we've resolved this by updating to the latest upstream release on Feb 17, [v2.3.3](https://github.com/pulumi/pulumi-civo/releases/tag/v2.3.3). Let us know if this isn't resolved, and we'll connect this issue with an issue upstream to track.

**Comment by nicolasochem** [comment]
thanks! I moved on from civo so can't test.
